image: 415596832415.dkr.ecr.us-west-2.amazonaws.com/cm_tech/docker-ruby-ci-image:2.6.3-extjs-7-20191018143452

services:
  - "postgres:9.6"
  - "redis:5.0.6-alpine"

before_script:
  - time bundle install --jobs $(nproc) --path vendor "${FLAGS[@]}"
  - cp ./spec/dummy/config/database.ci.yml ./spec/dummy/config/database.yml
  - RAILS_ENV=test bundle exec rails db:create db:migrate

.base-test:
  # Cancel if new commits where pushed
  interruptible: true
  # Run only when there is an MR
  only:
    - merge_requests

  stage: test

  # Use only the following CI runners
  tags:
    - gitlabci-runner-eks-shared-dev

rubocop:
  extends: .base-test
  script:
    - bundle exec rubocop

rspec-without-features:
  extends: .base-test
  script:
    - bundle exec rspec --exclude-pattern "spec/features/**/*_spec.rb"

rspec-features-1:
  extends: .base-test
  script:
    - ln -s /opt/support/extjs /cm_tech/marty/spec/dummy/public/extjs
    - bundle exec rspec spec/features --tag ~speed

rspec-features-2:
  extends: .base-test
  script:
    - ln -s /opt/support/extjs /cm_tech/marty/spec/dummy/public/extjs
    - bundle exec rspec spec/features --tag speed:slow

rspec-features-3:
  extends: .base-test
  script:
    - ln -s /opt/support/extjs /cm_tech/marty/spec/dummy/public/extjs
    - bundle exec rspec spec/features --tag speed:super_slow

cache:
  key: 'marty_bundler_cache'
  paths:
    - vendor/ruby

variables:
  BUNDLER_VERSION: "2.0.1"
  DOCKER_AUTH_CONFIG: '{ "credsStore": "ecr-login" }'
  GIT_SSL_NO_VERIFY: "true"
  HEADLESS: "true"
  HEADLESS_WINDOW_SIZE: "1400,1400"
  PGTZ: "America/Los_Angeles"
  POSTGRES_USER: "runner"
  POSTGRES_PASSWORD: ""
  MARTY_REDIS_URL: 'localhost:6379/1'
  RAILS_ENV: "test"
  RAILS_DUMP_SCHEMA: "false"
  REPOSITORY_URL: '415596832415.dkr.ecr.us-west-2.amazonaws.com/cm_tech/docker-ruby-ci-image'
  RSPEC_AUTO_RETRY_JS: "true"

