variables:
  COVERAGE: "true"
  GIT_SSL_NO_VERIFY: "true"
  MARTY_REDIS_URL: 'localhost:6379/1'
  PG_IMAGE_VERSION: "11"
  RAILS_DUMP_SCHEMA: "false"
  REDIS_IMAGE_VERSION: "latest"
  RUBY_IMAGE_VERSION: "latest"

# Redefining it here since it's different from other projects
.marty-rspec-rails: &marty-rspec-rails
  extends:
    - .base-rails
    - .base-rspec
  before_script:
    - mkdir -p spec/dummy/public/ && ln -s $EXTJS_PATH spec/dummy/public/
    - cp ./spec/dummy/config/database.ci.yml ./spec/dummy/config/database.yml
    - bundle exec rake db:create db:migrate app:assets:precompile

setup:
  extends: .setup

rubocop:
  extends: .rubocop

eslint-prettier:
  extends: .eslint-prettier

schema-lint:
  stage: check
  extends:
    - .schema-lint
    - .marty-rspec-rails
  variables:
    POSTGRES_DB_NAME: "marty_test"

rspec-controllers:
  extends:
    - .rspec-controllers
    - .marty-rspec-rails

rspec-features-normal:
  extends:
    - .rspec-features
    - .marty-rspec-rails
  script: bundle exec rspec spec/features --tag ~speed --format documentation

rspec-features-slow:
  extends:
    - .rspec-features
    - .marty-rspec-rails
  script: bundle exec rspec spec/features --tag speed:slow --format documentation

rspec-features-super-slow:
  extends:
    - .rspec-features
    - .marty-rspec-rails
  script: bundle exec rspec spec/features --tag speed:super_slow --format documentation

rspec-jobs:
  extends:
    - .rspec-jobs
    - .marty-rspec-rails

rspec-lib:
  extends:
    - .rspec-lib
    - .marty-rspec-rails

rspec-models:
  extends:
    - .rspec-models
    - .marty-rspec-rails

rspec-other:
  extends:
    - .rspec-other
    - .marty-rspec-rails

rspec-performance:
  extends:
    - .rspec-performance
    - .marty-rspec-rails
  services:
    - "postgres:$PG_IMAGE_VERSION"
    - "redis:$REDIS_IMAGE_VERSION"

rspec-requests:
  extends:
    - .rspec-requests
    - .marty-rspec-rails

rspec-services:
  extends:
    - .rspec-services
    - .marty-rspec-rails

code-coverage:
  extends: .code-coverage
  variables:
    RAILS_ENV: test
  before_script:
    - cp ./spec/dummy/config/database.ci.yml ./spec/dummy/config/database.yml
    - bundle exec rake db:create db:migrate
  script: bundle exec rake app:marty:merge_coverage_reports

include:
  - project: 'cm_tech/cm_shared'
    ref: needs_and_dependencies
    file: '/.gitlab/ci/defaults.yml'
