inherit_from: .rubocop_todo.yml
require: rubocop-performance

AllCops:
  TargetRubyVersion: 2.4.2
  Exclude:
    - 'db/**/*'
    - 'spec/dummy/**/*'
    - 'bin/{rails,rake}'
    - 'vendor/**/*'
    - 'lib/tasks/marty_tasks.rake'
    - !ruby/regexp /old_and_unused\.rb$/

Layout/DotPosition:
  EnforcedStyle: 'trailing'

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes

Metrics/BlockLength:
  Max: 400
  Exclude:
    - 'spec/**/*'

Style/CaseEquality:
  Exclude:
    - 'app/components/marty/report_form.rb'
    - 'app/models/marty/data_grid.rb'
    - 'app/helpers/marty/enum_helper.rb'
    - 'lib/marty/data_change.rb'
    - 'lib/marty/data_conversion.rb'
    - 'lib/marty/mcfly_model.rb'
    - 'lib/marty/monkey.rb'
    - 'other/marty/api/base.rb'
    - 'spec/lib/mcfly_model_spec.rb'

Lint/UnusedMethodArgument:
  AllowUnusedKeywordArguments: true
  IgnoreEmptyMethods: true

Style/SymbolArray:
  EnforcedStyle: brackets

# Marshal serialisation is used in Redis caching
Security/MarshalLoad:
  Exclude:
    - 'lib/marty/cache_adapters/redis.rb'
