inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - 'db/**/*'
    - 'spec/dummy/**/*'
    - 'bin/{rails,rake}'
    - 'vendor/**/*'
    - 'lib/tasks/marty_tasks.rake'
    - !ruby/regexp /old_and_unused\.rb$/

