inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.3.3
  Exclude:
    - 'db/**/*'
    - 'spec/dummy/**/*'
    - 'bin/{rails,rake}'
    - 'vendor/**/*'
    - 'lib/tasks/marty_tasks.rake'
    - !ruby/regexp /old_and_unused\.rb$/

Layout/DotPosition:
  EnforcedStyle: 'trailing'

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes

Metrics/BlockLength:
  Max: 400
  Exclude:
    - 'spec/**/*'

