language: ruby
rvm:
  - 1.9.3
  - 2.2.2

before_script:
  - cp config/database.yml.travis spec/dummy/config/database.yml
  - psql -c 'create database travis_ci_test;' -U postgres
  - bundle exec rake db:migrate

script:
  - export DISPLAY=:99.0
  - bundle exec rake

addons:
  postgresql: "9.4"
