version: "2"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dummy
    command: bash -c 'cd spec/dummy && rm -f tmp/pids/server.pid && rails s -b 0.0.0.0'
    ports:
      - "3000:3000"
    environment:
      - "PORT=3000"
      - "PATH=/bundle_box/bundle/bin:/usr/local/bundle/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
      - "DEVELOPMENT_DATABASE_URL=postgres://postgres@postgres/marty_dev"
      - "TEST_DATABASE_URL=postgres://postgres@postgres/marty_test"
      - "HEADLESS_WINDOW_SIZE=1920,1400"
      - "HEADLESS=true"
      - "PGTZ=America/Los_Angeles"
      - "BUNDLER_VERSION=2.1.4"
      - "MARTY_REDIS_URL=redis:6379/1"
      - "POSTGRES_HOST=postgres"
    # env_file: ".rbenv-vars"
    depends_on:
      - "postgres"
      - "redis"
    volumes:
      - .:/opt/app:delegated
      - '.bash_history.docker:/root/.bash_history'
      - '.pry_history.docker:/root/.pry_history'
      - '.ssh-docker:/root/.ssh'
      - bundle_box:/bundle_box
    tty: true
    stdin_open: true

  postgres:
    image: "postgres:11"
    ports:
      - "3030:5432"
    volumes:
      - postgresql-data:/var/lib/postgresql/data

  redis:
    image: 'redis:5.0.6-alpine'
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  bundle_box:
  postgresql-data:
  redis-data:

