version: "2"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dummy
    command: bash -c 'cd spec/dummy && rm -f tmp/pids/server.pid && rails s -b 0.0.0.0'
    ports:
      - "3000:3000"
    environment:
      - "PORT=3000"
      - "PATH=/bundle_box/bundle/bin:/usr/local/bundle/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
      - "DEVELOPMENT_DATABASE_URL=postgres://postgres@postgres/marty_dev"
      - "TEST_DATABASE_URL=postgres://postgres@postgres/marty_test"
      - "HEADLESS_WINDOW_SIZE=1400,1400"
      - "HEADLESS=true"
      - "PGTZ=America/Los_Angeles"
      - "BUNDLER_VERSION=2.0.1"
    # env_file: ".rbenv-vars"
    depends_on:
      - "postgres"
    volumes:
      - .:/opt/app:delegated

      # - '~/.bash_history:/root/.bash_history'
      # - '~/.pry_history:/root/.pry_history'
    volumes_from:
      - bundle_box
    tty: true
    stdin_open: true

  postgres:
    image: "clkao/postgres-plv8:9.6-2.0"
    volumes:
      - postgresql-data:/var/lib/postgresql/data

  bundle_box:
    image: busybox
    volumes:
      - /bundle_box

volumes:
  postgresql-data:

