# Fill this out if you want to use the Marty::SqlServer specs
SQLSERVER_<%= Rails.env %>:
  sqlserver: true
  host:         #
  database:     #
  username:     #
  password:     #
  test_command: #

common: &common
  adapter: postgresql
  encoding: utf8
  database: marty_dev
  host: 127.0.0.1
  pool: 5

test:
  <<: *common
  database: marty_test
  host: 127.0.0.1
  username: runner

