Delay:
    count  =?
    # the delay parameter delays the next created job so that a different
    # worker is more likely to claim it
    delay  =? 2.6
    ver    = Marty::Helper.sleep(delay) && Diagnostic::Helper.git
    res    = [(Delay() | "ver") for i in Marty::Helper.range_step(0, count, 1)]
    result = [r.to_a for r in res]

VersionDelay:
    count =?
    result = Delay(count=count) | "result"
